MyLaptopStoreApp/Controllers/AccountsController.cs
using IdentitySecuredApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace IdentitySecuredApp.Controllers
{
    public class AccountsController : Controller
    {
        UserManager<IdentityUser> _userManager = null;
        SignInManager<IdentityUser> _signInManager = null;
        public AccountsController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            this._userManager = userManager;
            this._signInManager = signInManager;
        }
       
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            var user = new IdentityUser { UserName = model.Email, Email = model.Email };
            var result = await _userManager.CreateAsync(user, model.Password);
            if (result.Succeeded)
            {
                await _signInManager.SignInAsync(user, isPersistent: false);
                ViewBag.msg = "User registerd successfully...";
                return RedirectToAction("UserIndex", "Laptops");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View();
        }


        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);
            if (result.Succeeded)
            {
                //session to be created after successfull login
                HttpContext.Session.SetString("uname", model.Email);
                ViewBag.msg = "Login success...";
                return RedirectToAction("UserIndex","Laptops");

            }
            else
            {
                ViewBag.msg = "invalid input credentials...";
            }
            return View();
        }
      public IActionResult DashBoard()
        {
            if (HttpContext.Session.GetString("uname") != null)
            {
                string name = HttpContext.Session.GetString("uname");
                ViewBag.msg = $"hello {name} ,welcome to dashboard....";
            }
            else
            {
                ViewBag.msg=$"Landed on this page by a technique ! Invalid";
            }
            return View();
        }
        public IActionResult Logout()
        {
            if (HttpContext.Session.GetString("uname") != null)
            {
                string name = HttpContext.Session.GetString("uname");
                ViewBag.msg = $"hello {name} , log out was succesfull";
                HttpContext.Session.Clear();
            }
            else
            {
                ViewBag.msg = $"No user available to logout...";
            }
            return View();
        }

    }
}

MyLaptopStoreApp/Controllers/AdminController.cs
using IdentitySecuredApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentitySecuredApp.Controllers
{
    public class AdminController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
       
        [HttpPost]
        public IActionResult Login(UserModel user)
        {
            if (user.UserName=="admin" && user.Password=="admin")
            {
                return RedirectToAction("Index", "Laptops", new { uname = user.UserName });
            }
            else
                ViewBag.msg = "Invalid input credentials...";
            return View();
        }
        //public IActionResult dashboard(string uname)
        //{
        //    ViewBag.msg = $"Hello{uname},welcome to dashboard";
        //    return View();
        //}
    }
}

MyLaptopStoreApp/Controllers/SellerController.cs
using IdentitySecuredApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentitySecuredApp.Controllers
{
    public class SellerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        private bool ValidateUser(string uname, string pwd)
        {
            List<UserModel> users = new List<UserModel>()
            {
                new UserModel{UserName="Seller1",Password="Seller1@123"},
                new UserModel{UserName="Seller2",Password="Seller2@123"},
                new UserModel{UserName="Seller3",Password="Seller3@123"},
                new UserModel{UserName="Seller4",Password="Seller4@123"},
            };
            return users.Exists(x => x.UserName == uname && x.Password == pwd);
        }
        [HttpPost]
        public IActionResult Login(UserModel user)
        {
            if (ValidateUser(user.UserName, user.Password))
            {
                return RedirectToAction("SellerIndex", "Laptops", new { uname = user.UserName });
            }
            else
                ViewBag.msg = "Invalid input credentials...";
            return View();
        }
    }
}

MyLaptopStoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - The Laptop Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand">The Laptop Store</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Login">Admin Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Seller" asp-action="Login">Seller Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Login">User Login</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Accounts" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; Lavanya H P</p>
        <p>Software Engineer, Dover India</p>
        <ul class="list-inline">
            <li class="list-inline-item"><a asp-controller="Home" asp-action="Privacy">Privacy</a></li>
            <li class="list-inline-item"><a asp-controller="Home" asp-action="Privacy">Terms</a></li>
            <li class="list-inline-item"><a asp-controller="Home" asp-action="Home">Support</a></li>
        </ul>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>